name: "Tigris Artifact"
description: "Upload or download artifacts to/from Fly.io Tigris S3"

inputs:
  operation:
    description: "upload or download"
    required: true
  local_path:
    description: "Local path to upload or download to"
    required: true
  remote_path:
    description: "Path in the Tigris bucket"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Tigris Artifact Script
      shell: bash
      run: |
        set -e

        OPERATION="${{ inputs.operation }}"
        LOCAL_PATH="${{ inputs.local_path }}"
        REMOTE_PATH="${{ inputs.remote_path }}"

        if ! command -v aws &> /dev/null; then
          curl -s https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install
        fi

        : "${TIGRIS_ACCESS_KEY_ID:?Missing TIGRIS_ACCESS_KEY_ID}"
        : "${TIGRIS_SECRET_ACCESS_KEY:?Missing TIGRIS_SECRET_ACCESS_KEY}"
        : "${TIGRIS_ENDPOINT:?Missing TIGRIS_ENDPOINT}"
        : "${TIGRIS_BUCKET:?Missing TIGRIS_BUCKET}"

        aws configure set aws_access_key_id "$TIGRIS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$TIGRIS_SECRET_ACCESS_KEY"
        aws configure set default.region us-east-1
        aws configure set default.s3.endpoint_url "$TIGRIS_ENDPOINT"

        if [[ "$OPERATION" == "upload" ]]; then
          echo "Uploading artifact..."

          if [[ -d "$LOCAL_PATH" ]]; then
            tar -czf /tmp/artifact.tar.gz -C "$LOCAL_PATH" .
          elif [[ -f "$LOCAL_PATH" ]]; then
            tar -czf /tmp/artifact.tar.gz -C "$(dirname "$LOCAL_PATH")" "$(basename "$LOCAL_PATH")"
          else
            echo "Local path does not exist: $LOCAL_PATH"
            exit 1
          fi

          aws s3 cp /tmp/artifact.tar.gz "s3://${TIGRIS_BUCKET}/${REMOTE_PATH}"

        elif [[ "$OPERATION" == "download" ]]; then
          echo "Downloading artifact..."
          aws s3 cp "s3://${TIGRIS_BUCKET}/${REMOTE_PATH}" /tmp/artifact.tar.gz
          mkdir -p "$LOCAL_PATH"
          tar -xzf /tmp/artifact.tar.gz -C "$LOCAL_PATH"

        else
          echo "Invalid operation: $OPERATION"
          exit 1
        fi
