name: "Tigris Artifact"
description: "Upload or download artifacts to/from Fly.io Tigris using rclone"

inputs:
  operation:
    description: "upload or download"
    required: true
  local_path:
    description: "Local file or directory"
    required: true
  remote_path:
    description: "Object path in the Tigris bucket"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Tigris Artifact Script
      shell: bash
      run: |
        set -euo pipefail

        OPERATION="${{ inputs.operation }}"
        LOCAL_PATH="${{ inputs.local_path }}"
        REMOTE_PATH="${{ inputs.remote_path }}"

        : "${TIGRIS_ACCESS_KEY_ID:?Missing TIGRIS_ACCESS_KEY_ID}"
        : "${TIGRIS_SECRET_ACCESS_KEY:?Missing TIGRIS_SECRET_ACCESS_KEY}"
        : "${TIGRIS_ENDPOINT:?Missing TIGRIS_ENDPOINT}"
        : "${TIGRIS_BUCKET:?Missing TIGRIS_BUCKET}"

        # -------------------------------
        # Install rclone (cross-platform)
        # -------------------------------
        if ! command -v rclone >/dev/null 2>&1; then
          echo "Installing rclone on $RUNNER_OS"

          if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS" ]]; then
            curl -fsSL https://rclone.org/install.sh | sudo bash

          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            curl -fsSL https://downloads.rclone.org/rclone-current-windows-amd64.zip -o rclone.zip
            unzip -q rclone.zip
            mkdir -p /usr/local/bin
            cp rclone-*/rclone.exe /usr/local/bin/rclone.exe

          else
            echo "Unsupported OS: $RUNNER_OS"
            exit 1
          fi
        fi

        # -------------------------------
        # rclone config (ephemeral)
        # -------------------------------
        mkdir -p ~/.config/rclone

        cat > ~/.config/rclone/rclone.conf <<EOF
        [tigris]
        type = s3
        provider = Other
        access_key_id = ${TIGRIS_ACCESS_KEY_ID}
        secret_access_key = ${TIGRIS_SECRET_ACCESS_KEY}
        endpoint = ${TIGRIS_ENDPOINT}
        force_path_style = true
        acl = private
        EOF

        # -------------------------------
        # Upload / Download
        # -------------------------------
        if [[ "$OPERATION" == "upload" ]]; then
          echo "Uploading to Tigris..."

          if [[ ! -e "$LOCAL_PATH" ]]; then
            echo "Local path does not exist: $LOCAL_PATH"
            exit 1
          fi

          rclone copy "$LOCAL_PATH" \
            "tigris:${TIGRIS_BUCKET}/${REMOTE_PATH}" \
            --progress

        elif [[ "$OPERATION" == "download" ]]; then
          echo "Downloading from Tigris..."

          mkdir -p "$LOCAL_PATH"

          rclone copy \
            "tigris:${TIGRIS_BUCKET}/${REMOTE_PATH}" \
            "$LOCAL_PATH" \
            --progress

        else
          echo "Invalid operation: $OPERATION"
          exit 1
        fi
