name: "Tigris Artifact"
description: "Upload or download artifacts to/from Fly.io Tigris S3"

inputs:
  operation:
    description: "upload or download"
    required: true
  local_path:
    description: "Local path to upload or download to"
    required: true
  remote_path:
    description: "Path in the Tigris bucket"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Tigris Artifact Script
      shell: bash
      run: |
        set -euo pipefail

        OPERATION="${{ inputs.operation }}"
        LOCAL_PATH="${{ inputs.local_path }}"
        REMOTE_PATH="${{ inputs.remote_path }}"

        AWS_VERSION="$(aws --version 2>/dev/null || true)"

        if [[ ! "$AWS_VERSION" =~ aws-cli/2 ]]; then
          echo "Installing AWS CLI v2..."
          curl -s https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
        fi


        # Required environment variables
        : "${TIGRIS_ACCESS_KEY_ID:?Missing TIGRIS_ACCESS_KEY_ID}"
        : "${TIGRIS_SECRET_ACCESS_KEY:?Missing TIGRIS_SECRET_ACCESS_KEY}"
        : "${TIGRIS_ENDPOINT:?Missing TIGRIS_ENDPOINT}"
        : "${TIGRIS_BUCKET:?Missing TIGRIS_BUCKET}"

        # Configure credentials only (no AWS region / endpoint config)
        aws configure set aws_access_key_id "$TIGRIS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$TIGRIS_SECRET_ACCESS_KEY"

        ARTIFACT="/tmp/artifact.tar.gz"

        if [[ "$OPERATION" == "upload" ]]; then
          echo "Uploading artifact to Tigris..."

          if [[ -d "$LOCAL_PATH" ]]; then
            tar -czf "$ARTIFACT" -C "$LOCAL_PATH" .
          elif [[ -f "$LOCAL_PATH" ]]; then
            tar -czf "$ARTIFACT" -C "$(dirname "$LOCAL_PATH")" "$(basename "$LOCAL_PATH")"
          else
            echo "Local path does not exist: $LOCAL_PATH"
            exit 1
          fi

          aws s3 cp "$ARTIFACT" "s3://${TIGRIS_BUCKET}/${REMOTE_PATH}" \
            --endpoint-url "$TIGRIS_ENDPOINT" \
            --no-multipart

        elif [[ "$OPERATION" == "download" ]]; then
          echo "Downloading artifact from Tigris..."

          aws s3 cp "s3://${TIGRIS_BUCKET}/${REMOTE_PATH}" "$ARTIFACT" \
            --endpoint-url "$TIGRIS_ENDPOINT"

          mkdir -p "$LOCAL_PATH"
          tar -xzf "$ARTIFACT" -C "$LOCAL_PATH"

        else
          echo "Invalid operation: $OPERATION"
          exit 1
        fi