name: "Tigris Artifact"
description: "Upload or download artifacts to/from Fly.io Tigris using rclone"

inputs:
  operation:
    description: "upload or download"
    required: true
  local_path:
    description: "Local path to upload or download to"
    required: true
  remote_path:
    description: "Path in the Tigris bucket"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Tigris Artifact Script (rclone)
      shell: bash
      run: |
        set -euo pipefail

        OPERATION="${{ inputs.operation }}"
        LOCAL_PATH="${{ inputs.local_path }}"
        REMOTE_PATH="${{ inputs.remote_path }}"

        # Required env vars
        : "${TIGRIS_ACCESS_KEY_ID:?Missing TIGRIS_ACCESS_KEY_ID}"
        : "${TIGRIS_SECRET_ACCESS_KEY:?Missing TIGRIS_SECRET_ACCESS_KEY}"
        : "${TIGRIS_ENDPOINT:?Missing TIGRIS_ENDPOINT}"
        : "${TIGRIS_BUCKET:?Missing TIGRIS_BUCKET}"

        # Install rclone if missing
        if ! command -v rclone >/dev/null 2>&1; then
          curl -fsSL https://rclone.org/install.sh | sudo bash
        fi

        # Create rclone config (ephemeral)
        mkdir -p ~/.config/rclone

        cat > ~/.config/rclone/rclone.conf <<EOF
        [tigris]
        type = s3
        provider = Other
        access_key_id = ${TIGRIS_ACCESS_KEY_ID}
        secret_access_key = ${TIGRIS_SECRET_ACCESS_KEY}
        endpoint = ${TIGRIS_ENDPOINT}
        acl = private
        force_path_style = true
        EOF

        if [[ "$OPERATION" == "upload" ]]; then
          echo "Uploading artifact to Tigris..."

          if [[ ! -e "$LOCAL_PATH" ]]; then
            echo "Local path does not exist: $LOCAL_PATH"
            exit 1
          fi

          rclone copy "$LOCAL_PATH" \
            "tigris:${TIGRIS_BUCKET}/${REMOTE_PATH}" \
            --progress

        elif [[ "$OPERATION" == "download" ]]; then
          echo "Downloading artifact from Tigris..."

          mkdir -p "$LOCAL_PATH"

          rclone copy \
            "tigris:${TIGRIS_BUCKET}/${REMOTE_PATH}" \
            "$LOCAL_PATH" \
            --progress

        else
          echo "Invalid operation: $OPERATION"
          exit 1
        fi
